Creating build stage

diff --git a/pipeline.yml b/pipeline.yml
--- a/pipeline.yml
+++ b/pipeline.yml
@@ -7,6 +7,12 @@ resources:
     branch: master
     private_key: ((github.private_key))
     uri: git@github.com:springernature/accessibility-guide.git
+- name: artifacts-frontenddevs-accessibility-guidelines
+  type: gcp-resource
+  source:
+    bucket: ((halfpipe-artifacts.bucket))
+    folder: frontenddevs/accessibility-guidelines
+    json_key: ((halfpipe-artifacts.private_key))
 - name: CF dev frontenddevs dev
   type: cf-resource
   source:
@@ -24,6 +30,13 @@ resources:
     space: live
     username: ((cloudfoundry.username))
 resource_types:
+- name: gcp-resource
+  type: registry-image
+  source:
+    password: ((gcr.private_key))
+    repository: eu.gcr.io/halfpipe-io/gcp-resource
+    tag: stable
+    username: _json_key
 - name: cf-resource
   type: registry-image
   source:
@@ -32,11 +45,100 @@ resource_types:
     tag: stable
     username: _json_key
 jobs:
-- name: deploy to dev
+- name: build
   serial: true
   plan:
   - aggregate:
     - get: git
+      trigger: true
+    timeout: 1h
+  - task: build
+    config:
+      platform: linux
+      image_resource:
+        type: registry-image
+        source:
+          repository: ruby
+          tag: 2.6.3
+      params:
+        ARTIFACTORY_PASSWORD: ((artifactory.password))
+        ARTIFACTORY_URL: ((artifactory.url))
+        ARTIFACTORY_USERNAME: ((artifactory.username))
+      run:
+        path: /bin/sh
+        args:
+        - -c
+        - |-
+          which bash > /dev/null
+          if [ $? != 0 ]; then
+            echo "WARNING: Bash is not present in the docker image"
+            echo "If your script depends on bash you will get a strange error message like:"
+            echo "  sh: yourscript.sh: command not found"
+            echo "To fix, make sure your docker image contains bash!"
+            echo ""
+            echo ""
+          fi
+
+          if [ -e /etc/alpine-release ]
+          then
+            echo "WARNING: you are running your build in a Alpine image or one that is based on the Alpine"
+            echo "There is a known issue where DNS resolving does not work as expected"
+            echo "https://github.com/gliderlabs/docker-alpine/issues/255"
+            echo "If you see any errors related to resolving hostnames the best course of action is to switch to another image"
+            echo "we recommend debian:stretch-slim as an alternative"
+            echo ""
+            echo ""
+          fi
+
+          copyArtifact() {
+            ARTIFACT=$1
+            ARTIFACT_OUT_PATH=$2
+            if [ -d $ARTIFACT ] ; then
+              mkdir -p $ARTIFACT_OUT_PATH/$ARTIFACT
+              cp -r $ARTIFACT/. $ARTIFACT_OUT_PATH/$ARTIFACT/
+            elif [ -f $ARTIFACT ] ; then
+              ARTIFACT_DIR=$(dirname $ARTIFACT)
+              mkdir -p $ARTIFACT_OUT_PATH/$ARTIFACT_DIR
+              cp $ARTIFACT $ARTIFACT_OUT_PATH/$ARTIFACT_DIR
+            else
+              echo "ERROR: Artifact '$ARTIFACT' not found. Try fly hijack to check the filesystem."
+              exit 1
+            fi
+          }
+
+          export GIT_REVISION=`cat .git/ref`
+
+          ./build.sh
+          EXIT_STATUS=$?
+          if [ $EXIT_STATUS != 0 ] ; then
+            exit 1
+          fi
+
+          # Artifacts to copy from task
+          copyArtifact ./_site ../artifacts-out
+        dir: git
+      inputs:
+      - name: git
+      outputs:
+      - name: artifacts-out
+      caches:
+      - path: ../../../var/halfpipe/cache
+      - path: ../../../halfpipe-cache
+    timeout: 1h
+    attempts: 1
+  - put: artifacts
+    resource: artifacts-frontenddevs-accessibility-guidelines
+    params:
+      folder: artifacts-out
+      version_file: git/.git/ref
+    timeout: 1h
+- name: deploy-to-dev
+  serial: true
+  plan:
+  - aggregate:
+    - get: git
+      passed:
+      - build
       trigger: true
     timeout: 1h
   - put: cf halfpipe-push
@@ -68,13 +170,13 @@ jobs:
       timeout: 1h
     timeout: 1h
     attempts: 2
-- name: deploy to live
+- name: deploy-to-live
   serial: true
   plan:
   - aggregate:
     - get: git
       passed:
-      - deploy to dev
+      - deploy-to-dev
       trigger: true
     timeout: 1h
   - put: cf halfpipe-push
